workflows:
    sample-workflow:
        name: Godot Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            ios_signing:
                distribution_type: development
                bundle_identifier: io.github.q962.Dodge-the-Creeps
            groups:
                - godot
            vars:
                BUNDLE_ID: io.github.q962.Dodge-the-Creeps
                GODOT_VERSION: 4.2.1
                GODOT_EXEC_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
                GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
                GODOT_TEMPLATES_DIR: "/Users/builder/Library/Application Support/Godot/export_templates"
                GODOT_EXEC: Godot.app/Contents/MacOS/Godot
                EXPORT_TYPE: iOS
                ARTIFACT: app.ipa
            xcode: 14.2
        scripts:
            - name: Download Godot engine
              script: |
                  curl -L -o ./godot.zip ${GODOT_EXEC_URL} && unzip ./godot.zip
            - name: Download Godot templates
              script: |
                  curl -L -o ./godot-templates.zip ${GODOT_TEMPLATES_URL} && unzip ./godot-templates.zip
            - name: Setup templates
              script: |
                  mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable"
            - name: Prepare build directory
              script: mkdir build/
            - name: Export project
              script: ${GODOT_EXEC} --path . --headless --export-debug "${EXPORT_TYPE}" build/${ARTIFACT}
            - name: Decode export presets
              script: echo ${GODOT_EXPORT_PRESETS} | base64 --decode > ./export_presets.cfg
        artifacts:
            - build/*.zip
